# FloatingText plugin for PocketMine-MP
# Author: TheNewManu

# Amount of time in seconds to refresh the FloatingTexts
update-time: 1

# List of ConfigTexts. Example:
# "TextName": "text"
# Tags: {player_name}, {player_health}, {player_max_health}, {online_players}, {max_online_players}, {server_name}, {line}
texts:
  "Text1": "Hello {player}"
  "Text2": "Your health: {health}"